### ISSUE TITLE
pages needed 

### ISSUE THREAD

**Issue by Fgonzalez512** [cwkatzmann/reddit_collab#1]
these are the pages I'm going to create under the views folder with a quick description of each. If you have questions hit me up. 

landing page        views/index
login page           views/login
sign up page        views/signup

all posts page     views/posts
single post    views/single-post
users' posts       views/user-posts
edit post          views/edit-post
new post           views/new-post

edit comment       views/edit-comment

**\* adding all comments made by user        views/all-comments

**Comment by rvarela11** [comment]
@d4rkkn1gh787 Are we including a 

- all comments page by user
- all comments by different usr
- single comment

I have the notes on user stories
